name: Lint docs
on: [push]
jobs:
  docs:
    name: Lint docs
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Markdown Lint
        run: |
          cd docs
          npx markdownlint-cli  content/