name: Build MSI packages for Windows
on:
  push:
    tags:
      - "*"
jobs:
  release:
    name: Build MSI packages for Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Creates and publish MSI
        run: .github/scripts/msi-build.ps1
      - name: Test the MSI by install, and uninstallation
        run: .github/scripts/msi-test.ps1
      - name: Publish the MSI
        env:
          MSI_UPLOAD_TOKEN: ${{ secrets.MSI_UPLOAD_TOKEN }}
          DOWNLOAD_SERVER: ${{ secrets.DOWNLOAD_SERVER }}
        run: .github/scripts/msi-publish.ps1