name: Test Server/Client Nix
on: [push]
jobs:
  test:
    name: Test Server/Client Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install caddy
        run: |
          sudo curl -L "https://caddyserver.com/api/download?os=linux&arch=amd64" -o /usr/bin/caddy
          sudo chmod +x /usr/bin/caddy
          /usr/bin/caddy version

      - name: Test
        run: go test -race -v ./...
