name: Lint
on: [push]
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - uses: actions/checkout@v2

      - name: golangci-lint
        shell: bash
        run: |
          mkdir ~/bin
          curl -L https://github.com/golangci/golangci-lint/releases/download/v1.50.1/golangci-lint-1.50.1-linux-amd64.tar.gz -o /tmp/golangci-lint-1.50.1-linux-amd64.tar.gz
          tar xzf /tmp/golangci-lint-1.50.1-linux-amd64.tar.gz -C /tmp/
          mv /tmp/golangci-lint-1.50.1-linux-amd64/golangci-lint ~/bin
          echo "Running go mod vendor"
          go mod vendor
          ~/bin/golangci-lint version
          echo "Running ~/bin/golangci-lint run"
          ~/bin/golangci-lint run
