name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # fetch-depth: 0 is required for the change log to work correctly.
          # For the details please see https://goreleaser.com/ci/actions/
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Run GoReleaser for Rport Build
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --clean --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Rport Build Commit Info
        id: rport_commit_info
        run: |
          echo ::set-output name=commit_sha::$(git rev-parse HEAD)


      - name: Checkout, build and release Rport Plus
        id: rport_plus_build
        env:
          RPORT_GIT_REF: ${{github.ref_name}}
          RPORT_COMMIT_ID: ${{ steps.rport_commit_info.outputs.commit_sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RPORT_PLUS_PRIV_KEY: ${{ secrets.RPORT_PLUS_PRIV_KEY }}
        run: | 
          bash .github/scripts/build-plus.sh
          bash .github/scripts/release-plus.sh

      - name: Create RPM and DEB packages
        id: create_pkgs
        run: bash opt/fpm/package.sh

      - name: Publish RPM and DEB packages
        id: publish_pkgs
        env:
          REPO_SSH_PRIV_KEY: ${{ secrets.REPO_SSH_PRIV_KEY }}
          REPO_SSH_PORT: ${{ secrets.REPO_SSH_PORT }}
          REPO_SSH_USER: ${{ secrets.REPO_SSH_USER }}
          REPO_SSH_HOST: ${{ secrets.REPO_SSH_HOST }}
          REPO_SSH_KNOWN_HOSTS: ${{ secrets.REPO_SSH_KNOWN_HOSTS }}
          REPO_GPG_KEY_ID: ${{ secrets.REPO_GPG_KEY_ID }}
        run: bash opt/fpm/publish.sh
