name: Build and run
on: [push]

jobs:
  build_n_run:
    name: Build and run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build
        # set rport version to {date-time}-{github-master-head-sha}
        env:
          RPORT_PLUS_PRIV_KEY: ${{ secrets.RPORT_PLUS_PRIV_KEY }}
        run: |
          echo "🚚 Building rport & rportd now ..."
          go build -v -ldflags="-X 'github.com/cloudradar-monitoring/rport/share.BuildVersion=$(date -u +%y.%m%d.%H%M)-$(git rev-parse HEAD)'"  -o ./ ./cmd/...
          echo "✅ Successfully build rport"
          echo "🚚 Building Plus Plugin now ..."
          bash .github/scripts/build-plus.sh
          ls -l /home/runner/work/rport/rport/rport-plus/rport-plus.so
          echo "✅ Successfully built the plus plugin"

      - name: Test Build
        shell: bash
        run: |
          bash .github/scripts/start_rportd.sh
          bash .github/scripts/start_rport.sh
